// <auto-generated />
namespace AspMVC5Training.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_GoogleAuthenticatorSecretKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_GoogleAuthenticatorSecretKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201705221552503_Add_GoogleAuthenticatorSecretKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
